import type { Metadata } from "next";
import localFont from "next/font/local";
import { Provider } from "@/providers/index";
import "./globals.css";
import { Sidebar } from "@/components/ui/sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-background text-foreground antialiased`}
      >
        <Provider>
          <div className="flex min-h-screen">
            <Sidebar>{/* Sidebar content goes here */}</Sidebar>
            <main className="flex-1 overflow-auto">{children}</main>
          </div>
        </Provider>
      </body>
    </html>
  );
}
