import type { Metadata } from "next";
import Image from "next/image";
import localFont from "next/font/local";
import { Provider } from "@/providers/index";
import "./globals.css";
import { Sidebar, SidebarHeader } from "@/components/ui/sidebar";
import { Menubar, MenubarMenu, MenubarTrigger } from "@/components/ui/menubar";
import Link from "next/link";
import { overviewRequest } from "./hooks/use-overview";
import { OverviewCard } from "@/components/ui/overview-card";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data } = await overviewRequest();
  return (
    <html lang="en" suppressHydrationWarning className="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-background text-foreground antialiased`}
      >
        <Provider>
          <div className="flex min-h-screen">
            <Sidebar>
              <SidebarHeader>
                <Image
                  className="dark:invert"
                  priority
                  src="/openblocklabs-logo.svg"
                  alt="OpenBlockLabs Logo"
                  width={100}
                  height={100}
                />
              </SidebarHeader>
            </Sidebar>
            <main className="flex-1 overflow-auto">
              <Menubar>
                <MenubarMenu>
                  <MenubarTrigger>
                    <Link href="/ecosystem-overview" className="w-full">
                      Ecosystem Overview
                    </Link>
                  </MenubarTrigger>
                </MenubarMenu>
                <MenubarMenu>
                  <MenubarTrigger>
                    <Link href="/avs" className="w-full">
                      AVS
                    </Link>
                  </MenubarTrigger>
                </MenubarMenu>
                <MenubarMenu>
                  <MenubarTrigger>
                    <Link href="/operators" className="w-full">
                      Operators
                    </Link>
                  </MenubarTrigger>
                </MenubarMenu>
                <MenubarMenu>
                  <MenubarTrigger>
                    <Link href="/restakers" className="w-full">
                      Restakers
                    </Link>
                  </MenubarTrigger>
                </MenubarMenu>
              </Menubar>
              <div className="mb-4 grid gap-4 md:grid-cols-2 lg:grid-cols-4">
                {data.map((card) => (
                  <OverviewCard key={card.title} title={card.title}>
                    <div className="text-2xl font-bold">{card.metric}</div>
                    <p className="text-xs text-green-400">
                      +2.0% from last month
                    </p>
                  </OverviewCard>
                ))}
              </div>
              {children}
            </main>
          </div>
        </Provider>
      </body>
    </html>
  );
}
