import type { Metadata } from "next";
import Image from "next/image";
import localFont from "next/font/local";
import { Provider } from "@/providers/index";
import "./globals.css";
import { Sidebar, SidebarHeader } from "@/components/ui/sidebar";
import { Menubar, MenubarMenu, MenubarTrigger } from "@/components/ui/menubar";
import Link from "next/link";
import { overviewRequest } from "./hooks/use-overview";
import { OverviewCard } from "@/components/ui/overview-card";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data } = await overviewRequest();
  return (
    <html lang="en" suppressHydrationWarning className="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-background text-foreground antialiased`}
      >
        <Provider>
          <div className="flex min-h-screen">
            <Sidebar>
              <SidebarHeader>
                <Image
                  className="dark:invert"
                  priority
                  src="/openblocklabs-logo.svg"
                  alt="OpenBlockLabs Logo"
                  width={100}
                  height={100}
                />
              </SidebarHeader>
            </Sidebar>
            <main className="flex-1 overflow-auto">
              <Breadcrumb>
                <BreadcrumbList>
                  <BreadcrumbItem>
                    <BreadcrumbLink href="/">EigenLayer</BreadcrumbLink>
                  </BreadcrumbItem>
                  <BreadcrumbSeparator />
                  <BreadcrumbItem>
                    <BreadcrumbLink href="/ecosystem-overview">
                      Ecosystem Overview
                    </BreadcrumbLink>
                  </BreadcrumbItem>
                </BreadcrumbList>
              </Breadcrumb>
              <Menubar>
                <MenubarMenu>
                  <MenubarTrigger>
                    <Link href="/ecosystem-overview" className="w-full">
                      Ecosystem Overview
                    </Link>
                  </MenubarTrigger>
                </MenubarMenu>
                <MenubarMenu>
                  <MenubarTrigger>
                    <Link href="/avs" className="w-full">
                      AVS
                    </Link>
                  </MenubarTrigger>
                </MenubarMenu>
                <MenubarMenu>
                  <MenubarTrigger>
                    <Link href="/operators" className="w-full">
                      Operators
                    </Link>
                  </MenubarTrigger>
                </MenubarMenu>
                <MenubarMenu>
                  <MenubarTrigger>
                    <Link href="/restakers" className="w-full">
                      Restakers
                    </Link>
                  </MenubarTrigger>
                </MenubarMenu>
              </Menubar>
              {children}
            </main>
          </div>
        </Provider>
      </body>
    </html>
  );
}
